#!/usr/bin/env python3
"""
Generate the breadboard ROW MAP + control-board MAP for the LPG layout straight
from the authoritative JSON, and inject them into the placement doc between
  <!-- GEN:MAPS:START --> ... <!-- GEN:MAPS:END -->
markers. Re-run after any layout change so the doc never drifts from lpg.json.

Net names are resolved exactly as cross_check_nets.py does it (IC pins anchor a
row-side; power rails by parity; everything else from BARE_ROW_NETS), so the two
files share one source of truth for nets.

Usage:
    python3 gen_rowmap.py [layouts/lpg.json] [../../docs/lpg_breadboard_placement.md]
"""
import json
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from cross_check_nets import BARE_ROW_NETS, power_rail_net, side  # noqa: E402

json_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'layouts/lpg.json')
doc_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, '../../docs/lpg_breadboard_placement.md')

layout = json.load(open(json_path))
rev = layout.get('revision', '?')

# (row, side) -> net, anchored by IC pins
rs_net = {}
for ic in layout['ics']:
    for p in ic['pins']:
        rs_net[(p['r'], side(p['c']))] = p['net']


def net_of(r, s):
    if s in ('pwrL', 'pwrR'):
        return power_rail_net(s, r)
    return rs_net.get((r, s)) or BARE_ROW_NETS.get((r, s)) or '—'


COLORD = {c: i for i, c in enumerate('abcde')}
COLORD.update({c: i for i, c in enumerate('fghij')})

occ = defaultdict(list)   # (row, side) -> [(col-order, text)]


def add(r, col, text):
    occ[(r, side(col))].append((COLORD.get(col, 0), text))


for ic in layout['ics']:
    for p in ic['pins']:
        add(p['r'], p['c'], f"**{ic['id']}.{p['n']}**@{p['c']}")
for c in layout['twoPins']:
    v = c.get('value', '')
    add(c['r1'], c['c1'], f"{c['id']}.1@{c['c1']} ({v})")
    add(c['r2'], c['c2'], f"{c['id']}.2@{c['c2']} ({v})")
for j in layout.get('jumpers', []):
    add(j['r1'], j['c1'], f"_{j['id']}_")
    add(j['r2'], j['c2'], f"_{j['id']}_")
for j in layout.get('jpsWires', []):
    mark = ' ⏚' if j.get('mark') == 'gnd' else (' ↔b' if j.get('mark') == 'link' else '')
    add(j['row'], j['col'], f"{j.get('lbl', j['id'])}{mark}")


def cell(r, s):
    return ', '.join(t for _, t in sorted(occ.get((r, s), [])))


# breadboard row map (main grid cols a-j, rows 1-36)
bb = ["| Row | Net (L) | Left half (a–e) | Net (R) | Right half (f–j) |",
      "|-----|---------|-----------------|---------|------------------|"]
for r in range(1, 37):
    L, R = cell(r, 'L'), cell(r, 'R')
    if not L and not R:
        continue
    bb.append(f"| {r} | `{net_of(r, 'L')}` | {L or '—'} | `{net_of(r, 'R')}` | {R or '—'} |")

# control-board map (ctrlL / ctrlR, rows 1-40)
cb = ["| Row | Left CTRL (ctrlL) | Right CTRL (ctrlR) |",
      "|-----|-------------------|--------------------|"]
for r in range(1, 41):
    L, R = cell(r, 'ctrlL'), cell(r, 'ctrlR')
    if not L and not R:
        continue
    cb.append(f"| {r} | {L or '—'} | {R or '—'} |")

parts = [
    f"<!-- GEN:MAPS:START — auto-generated by tools/visualizer/gen_rowmap.py from lpg.json rev {rev}. "
    f"Do not hand-edit between these markers; re-run the generator. -->",
    "",
    f"### Breadboard row map (cols a–j) — rev {rev}",
    "",
    *bb,
    "",
    f"### Control-board map (ctrlL / ctrlR) — rev {rev}",
    "",
    *cb,
    "",
    "<!-- GEN:MAPS:END -->",
]
block = "\n".join(parts)

doc = open(doc_path).read()
if 'GEN:MAPS:START' not in doc:
    print("ERROR: markers not found. Add a <!-- GEN:MAPS:START --> ... <!-- GEN:MAPS:END --> "
          "pair to the doc where the maps should go, then re-run.", file=sys.stderr)
    sys.exit(1)
new = re.sub(r"<!-- GEN:MAPS:START.*?GEN:MAPS:END -->", lambda m: block, doc, flags=re.S)
open(doc_path, 'w').write(new)
print(f"Injected maps from rev {rev}: {len(bb) - 2} breadboard rows, {len(cb) - 2} control rows.")
